### PR TITLE
Update Framework7 to 1.2.0

### PR DESCRIPTION
**Pull request by ebisbe**

### CODE REVIEW

**Comment by arvindr21** [comment]
Thanks for the PR @ebisbe 

Can you please check why the CI failed?

Logs
```
 framework7-phonegap generator
  ✓ can be imported without blowing up
  1 passing (2s)
  1 failing
  1) framework7-phonegap generator creates expected files:
     Error: timeout of 2000ms exceeded. Ensure the done() callback is being called in this test.
```

Thanks.

**Comment by ebisbe** [comment]
Hello, 
Yes, I saw it later and didn't get time to update and understand what happened. I will try to fix it now.

**Comment by ebisbe** [comment]
@arvindr21 Now it's all fine!

**Comment by ebisbe** [comment]
FYI I haven't include the apps/ folder with the two examples you had.

**Comment by arvindr21** [comment]
Thanks @ebisbe! Merged

**Pull request merged**
